from queries.queries import CREATE_TABLE_COOKIES, PROVISION_COOKIES, VALIDATE_ADMIN_COOKIE, VALIDATE_PLAY_TOKEN, \
    CREATE_TABLE_MESSAGES, GET_CHAT_HISTORY, SAVE_USER_MESSAGE, SAVE_SERVER_MESSAGE, GET_ADMIN_COOKIE
